name: sbt test and pact provider verification

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sbt-tests-and-pact-verification:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.1-alpine
        ports: 
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: install postgresql-client-13
      run:  |
        sudo apt update
        sudo apt -y install wget
        wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
        echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" | sudo tee  /etc/apt/sources.list.d/pgdg.list
        sudo apt update
        sudo apt -y install postgresql-client-13
    
    - name: pull pact-cli docker image
      run: docker pull pactfoundation/pact-cli:latest
    
    - name: setup-graalvm-ce
      uses: rinx/setup-graalvm-ce@v0.0.5
      with:
        graalvm-version: "20.2.0"
        java-version: "java8"
        native-image: "false"
    
    - name: checkout repo
      uses: actions/checkout@v2
    
    - name: scala tests
      run: sbt test
    
    - name: initialize database
      env:
        PGPASSWORD: postgres
      run: |
        psql -U postgres -h localhost -f src/main/resources/db/init.sql
        psql -U postgres -h localhost -f src/main/resources/db/ci.sql
    
    - name: run bilgge in bg with ci parameters
      env:
        JAVA_OPTS: -Dconfig.file=src/main/resources/ci.conf
      run: |
        sbt pack
        nohup ./target/pack/bin/bilgge > /dev/null 2>&1 &
        bilgge_pid=$!
    
    - name: pact provider verification
      env:
        PACT_BROKER_BASE_URL: ${{ secrets.PACT_BROKER_BASE_URL }}
        PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
      run: |
        docker run --rm --network host -e PACT_BROKER_BASE_URL -e PACT_BROKER_TOKEN -e PACT_BROKER_PUBLISH_VERIFICATION_RESULTS=true pactfoundation/pact-cli:latest verify --provider-base-url http://localhost:9092 --provider bilggeApi --provider-app-version 0.1.0
    
    - name: kill bilgge
      run: kill -2 $bilgge_pid
    
